import { FormEvent, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRightLeft, ClipboardList, History, PackagePlus, Plus, Save } from "lucide-react";
import { AppShell } from "../components/AppShell";
import { Button, Card, ErrorState, Input, LoadingState, Modal, Select } from "../components/ui";
import { DetailCard, EmptyPanel, FormField, PageHeader, PaginationBar, StatusBadge, Table, Toolbar } from "../components/phase1";
import { ApiError, apiRequest } from "../lib/api";
import { asNumber, type InventoryItem, type InventoryTransaction, type ListResult, type Product, type Transfer, type Warehouse } from "../lib/phase1";

function Options({ products, warehouses, value, setValue }: { products: Product[]; warehouses: Warehouse[]; value: Record<string, string>; setValue: (key: string, value: string) => void }) {
  return <div className="form-grid two-up"><FormField label="Product"><Select required value={value.productId ?? ""} onChange={(event) => setValue("productId", event.target.value)}><option value="">Select product</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</Select></FormField><FormField label="Warehouse"><Select required value={value.warehouseId ?? ""} onChange={(event) => setValue("warehouseId", event.target.value)}><option value="">Select warehouse</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</Select></FormField></div>;
}

function StockModal({ mode, onDone }: { mode: "initial" | "adjustment"; onDone: () => void }) {
  const [products, setProducts] = useState<Product[]>([]); const [warehouses, setWarehouses] = useState<Warehouse[]>([]);
  const [value, setValueState] = useState<Record<string, string>>({ direction: "IN" }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const setValue = (key: string, next: string) => setValueState((current) => ({ ...current, [key]: next }));
  useEffect(() => { Promise.all([apiRequest<ListResult<Product>>("/api/v1/products?active=true&pageSize=100"), apiRequest<ListResult<Warehouse>>("/api/v1/warehouses?active=true&pageSize=100")]).then(([productResult, warehouseResult]) => { setProducts(productResult.items); setWarehouses(warehouseResult.items); }).catch((err) => setError(err instanceof Error ? err.message : "Unable to load options.")); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setSaving(true); try { await apiRequest(`/api/v1/inventory/${mode === "initial" ? "initial-stock" : "adjustments"}`, { method: "POST", body: JSON.stringify({ ...value, quantity: Number(value.quantity), ...(mode === "initial" ? {} : { direction: value.direction }) }) }); onDone(); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to record stock."); } finally { setSaving(false); } }
  return <form className="form-stack" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<Options products={products} warehouses={warehouses} value={value} setValue={setValue} />{mode === "adjustment" && <FormField label="Direction"><Select value={value.direction} onChange={(event) => setValue("direction", event.target.value)}><option value="IN">Stock in</option><option value="OUT">Stock out</option></Select></FormField>}<FormField label="Quantity"><Input required type="number" min="1" value={value.quantity ?? ""} onChange={(event) => setValue("quantity", event.target.value)} /></FormField><FormField label="Reason"><Input required minLength={2} value={value.reason ?? ""} onChange={(event) => setValue("reason", event.target.value)} placeholder="Why is stock changing?" /></FormField><div className="modal-actions"><Button type="button" variant="secondary" onClick={onDone}>Cancel</Button><Button type="submit" disabled={saving}><Save size={15} />{saving ? "Saving..." : "Record movement"}</Button></div></form>;
}

export function InventoryPage() {
  const [result, setResult] = useState<ListResult<InventoryItem> | null>(null); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [error, setError] = useState(""); const [modal, setModal] = useState<"initial" | "adjustment" | null>(null);
  const load = () => apiRequest<ListResult<InventoryItem>>(`/api/v1/inventory?page=${page}&pageSize=20${query ? `&search=${encodeURIComponent(query)}` : ""}`).then(setResult).catch((err) => setError(err instanceof Error ? err.message : "Unable to load inventory."));
  useEffect(() => { setResult(null); setError(""); load(); }, [page, query]);
  return <AppShell><PageHeader eyebrow="Operations / Inventory" title="Inventory" description="See on-hand stock, availability, and value across every warehouse." action={<div className="button-group"><Button variant="secondary" onClick={() => setModal("adjustment")}><PackagePlus size={15} /> Adjust stock</Button><Button onClick={() => setModal("initial")}><Plus size={15} /> Initial stock</Button></div>} /><div className="quick-links"><Link to="/inventory/movements"><History size={16} /> Movement history</Link><Link to="/inventory/transfers"><ArrowRightLeft size={16} /> Warehouse transfers</Link></div><Card className="list-card"><Toolbar search={query} onSearch={(value) => { setQuery(value); setPage(1); }} placeholder="Search products or SKU"><span className="result-count">{result?.pagination.total ?? 0} stock records</span></Toolbar>{error ? <ErrorState message={error} /> : !result ? <LoadingState /> : result.items.length === 0 ? <EmptyPanel title="No inventory records" message="Record initial stock to start tracking inventory." onAdd={() => setModal("initial")} /> : <Table headers={["Product", "Warehouse", "On hand", "Available", "Inventory value"]}>{result.items.map((item) => <tr key={item.id}><td><span className="table-primary">{item.product.name}</span><small>{item.product.sku}</small></td><td>{item.warehouse.name}</td><td>{item.onHandQuantity}</td><td><strong className={item.availableQuantity <= item.product.minimumStock ? "text-warning" : ""}>{item.availableQuantity}</strong><small>Reserved {item.reservedQuantity}</small></td><td>{asNumber(item.inventoryValue).toLocaleString()} DZD</td></tr>)}</Table>}{result && <PaginationBar page={result.pagination.page} totalPages={result.pagination.totalPages} onPage={setPage} />}</Card><Modal open={Boolean(modal)} title={modal === "initial" ? "Record initial stock" : "Adjust stock"} onClose={() => setModal(null)}>{modal && <StockModal mode={modal} onDone={() => { setModal(null); setResult(null); load(); }} />}</Modal></AppShell>;
}

export function MovementsPage() {
  const [result, setResult] = useState<ListResult<InventoryTransaction> | null>(null); const [page, setPage] = useState(1); const [error, setError] = useState("");
  useEffect(() => { setResult(null); apiRequest<ListResult<InventoryTransaction>>(`/api/v1/inventory/transactions?page=${page}&pageSize=30`).then(setResult).catch((err) => setError(err instanceof Error ? err.message : "Unable to load movements.")); }, [page]);
  return <AppShell><PageHeader eyebrow="Operations / Inventory" title="Movement history" description="An auditable timeline of every stock change." back="/inventory" /><Card className="list-card">{error ? <ErrorState message={error} /> : !result ? <LoadingState /> : result.items.length === 0 ? <EmptyPanel title="No movements yet" message="Stock receipts, sales, adjustments, and transfers will appear here." /> : <Table headers={["Date", "Product", "Warehouse", "Movement", "Quantity", "Reason"]}>{result.items.map((item) => <tr key={item.id}><td>{new Date(item.createdAt).toLocaleDateString()}</td><td><span className="table-primary">{item.product.name}</span><small>{item.product.sku}</small></td><td>{item.warehouse.name}</td><td><StatusBadge status={item.type} /></td><td>{item.type.endsWith("_OUT") || item.type === "SALE" ? "-" : "+"}{item.quantity}</td><td>{item.reason ?? "—"}</td></tr>)}</Table>}{result && <PaginationBar page={result.pagination.page} totalPages={result.pagination.totalPages} onPage={setPage} />}</Card></AppShell>;
}

type TransferFormProps = { onDone: () => void };
function TransferForm({ onDone }: TransferFormProps) {
  const [products, setProducts] = useState<Product[]>([]); const [warehouses, setWarehouses] = useState<Warehouse[]>([]); const [value, setValue] = useState({ sourceWarehouseId: "", destinationWarehouseId: "", productId: "", quantity: "", notes: "" }); const [error, setError] = useState("");
  useEffect(() => { Promise.all([apiRequest<ListResult<Product>>("/api/v1/products?active=true&pageSize=100"), apiRequest<ListResult<Warehouse>>("/api/v1/warehouses?active=true&pageSize=100")]).then(([p, w]) => { setProducts(p.items); setWarehouses(w.items); }).catch((err) => setError(err instanceof Error ? err.message : "Unable to load options.")); }, []);
  const update = (key: string, next: string) => setValue((current) => ({ ...current, [key]: next }));
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); try { await apiRequest("/api/v1/inventory/transfers", { method: "POST", body: JSON.stringify({ sourceWarehouseId: value.sourceWarehouseId, destinationWarehouseId: value.destinationWarehouseId, notes: value.notes, items: [{ productId: value.productId, quantity: Number(value.quantity) }] }) }); onDone(); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to create transfer."); } }
  return <form className="form-stack" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<div className="form-grid two-up"><FormField label="From warehouse"><Select required value={value.sourceWarehouseId} onChange={(event) => update("sourceWarehouseId", event.target.value)}><option value="">Select warehouse</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</Select></FormField><FormField label="To warehouse"><Select required value={value.destinationWarehouseId} onChange={(event) => update("destinationWarehouseId", event.target.value)}><option value="">Select warehouse</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</Select></FormField></div><FormField label="Product"><Select required value={value.productId} onChange={(event) => update("productId", event.target.value)}><option value="">Select product</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</Select></FormField><FormField label="Quantity"><Input required type="number" min="1" value={value.quantity} onChange={(event) => update("quantity", event.target.value)} /></FormField><FormField label="Notes"><Input value={value.notes} onChange={(event) => update("notes", event.target.value)} /></FormField><div className="modal-actions"><Button type="button" variant="secondary" onClick={onDone}>Cancel</Button><Button type="submit"><Save size={15} /> Create transfer</Button></div></form>;
}

export function TransfersPage() {
  const [result, setResult] = useState<ListResult<Transfer> | null>(null); const [error, setError] = useState(""); const [modal, setModal] = useState(false);
  const load = () => apiRequest<ListResult<Transfer>>("/api/v1/inventory/transfers?pageSize=50").then(setResult).catch((err) => setError(err instanceof Error ? err.message : "Unable to load transfers."));
  useEffect(() => { load(); }, []);
  async function action(id: string, operation: "complete" | "cancel") { try { await apiRequest(`/api/v1/inventory/transfers/${id}/${operation}`, { method: "POST" }); load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update transfer."); } }
  return <AppShell><PageHeader eyebrow="Operations / Inventory" title="Warehouse transfers" description="Move stock between organization warehouses with a complete audit trail." back="/inventory" action={<Button onClick={() => setModal(true)}><Plus size={16} /> New transfer</Button>} /><Card className="list-card">{error && <ErrorState message={error} />}{!result ? <LoadingState /> : result.items.length === 0 ? <EmptyPanel title="No transfers yet" message="Create a transfer when inventory needs to be rebalanced." onAdd={() => setModal(true)} /> : <Table headers={["Transfer", "Route", "Items", "Status", "Created", "Actions"]}>{result.items.map((item) => <tr key={item.id}><td><span className="table-primary">TR-{item.id.slice(0, 8).toUpperCase()}</span><small>{item.actor ? `${item.actor.firstName} ${item.actor.lastName}` : ""}</small></td><td>{item.sourceWarehouse.name} <ArrowRightLeft size={13} /> {item.destinationWarehouse.name}</td><td>{item.items.reduce((sum, line) => sum + line.quantity, 0)} units</td><td><StatusBadge status={item.status} /></td><td>{new Date(item.createdAt).toLocaleDateString()}</td><td className="table-actions">{item.status === "PENDING" && <><Button variant="secondary" onClick={() => action(item.id, "complete")}>Complete</Button><Button variant="ghost" onClick={() => action(item.id, "cancel")}>Cancel</Button></>}</td></tr>)}</Table>}</Card><Modal open={modal} title="New warehouse transfer" onClose={() => setModal(false)}><TransferForm onDone={() => { setModal(false); setResult(null); load(); }} /></Modal></AppShell>;
}