import { FormEvent, useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Check, ChevronRight, Plus, Save, ShoppingCart, Truck } from "lucide-react";
import { AppShell } from "../components/AppShell";
import { Button, Card, ErrorState, Input, LoadingState, Modal, Select } from "../components/ui";
import { DetailCard, EmptyPanel, FormField, PageHeader, StatusBadge, Table, Toolbar } from "../components/phase1";
import { ApiError, apiRequest } from "../lib/api";
import { asNumber, type Contact, type ListResult, type Product, type PurchaseOrder, type SalesOrder, type Warehouse } from "../lib/phase1";

type OrderKind = "purchases" | "sales";
type Order = PurchaseOrder | SalesOrder;

function useOrderOptions(contactKind: "suppliers" | "customers") {
  const [products, setProducts] = useState<Product[]>([]); const [warehouses, setWarehouses] = useState<Warehouse[]>([]); const [contacts, setContacts] = useState<Contact[]>([]); const [error, setError] = useState("");
  useEffect(() => { Promise.all([apiRequest<ListResult<Product>>("/api/v1/products?active=true&pageSize=100"), apiRequest<ListResult<Warehouse>>("/api/v1/warehouses?active=true&pageSize=100"), apiRequest<ListResult<Contact>>(`/api/v1/${contactKind}?active=true&pageSize=100`)]).then(([productResult, warehouseResult, contactResult]) => { setProducts(productResult.items); setWarehouses(warehouseResult.items); setContacts(contactResult.items); }).catch((err) => setError(err instanceof Error ? err.message : "Unable to load order options.")); }, [contactKind]);
  return { products, warehouses, contacts, error };
}

function LineEditor({ products, lines, setLines, purchase }: { products: Product[]; lines: { productId: string; quantity: string; unitPrice: string }[]; setLines: (lines: { productId: string; quantity: string; unitPrice: string }[]) => void; purchase: boolean }) {
  return <div className="line-editor"><div className="section-label">Order lines</div>{lines.map((line, index) => <div className="line-row" key={index}><Select required value={line.productId} onChange={(event) => setLines(lines.map((current, lineIndex) => lineIndex === index ? { ...current, productId: event.target.value } : current))}><option value="">Select product</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</Select><Input required type="number" min="1" value={line.quantity} placeholder="Qty" onChange={(event) => setLines(lines.map((current, lineIndex) => lineIndex === index ? { ...current, quantity: event.target.value } : current))} /><Input type="number" min="0" step="0.01" value={line.unitPrice} placeholder={purchase ? "Buy price" : "Sell price"} onChange={(event) => setLines(lines.map((current, lineIndex) => lineIndex === index ? { ...current, unitPrice: event.target.value } : current))} /><Button type="button" variant="ghost" onClick={() => setLines(lines.filter((_, lineIndex) => lineIndex !== index))}>×</Button></div>)}<Button type="button" variant="secondary" onClick={() => setLines([...lines, { productId: "", quantity: "", unitPrice: "" }])}><Plus size={14} /> Add line</Button></div>;
}

function OrderForm({ kind, onDone }: { kind: OrderKind; onDone: () => void }) {
  const purchase = kind === "purchases"; const { products, warehouses, contacts, error: optionsError } = useOrderOptions(purchase ? "suppliers" : "customers");
  const [value, setValue] = useState({ contactId: "", warehouseId: "", expectedDeliveryDate: "", notes: "", status: purchase ? "DRAFT" : "DRAFT" }); const [lines, setLines] = useState([{ productId: "", quantity: "", unitPrice: "" }]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = (key: string, next: string) => setValue((current) => ({ ...current, [key]: next }));
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setSaving(true); try { await apiRequest(`/api/v1/${kind}`, { method: "POST", body: JSON.stringify(purchase ? { supplierId: value.contactId, warehouseId: value.warehouseId, expectedDeliveryDate: value.expectedDeliveryDate ? new Date(value.expectedDeliveryDate).toISOString() : "", notes: value.notes, status: value.status, items: lines.map((line) => ({ productId: line.productId, quantity: Number(line.quantity), unitPrice: line.unitPrice ? Number(line.unitPrice) : undefined })) } : { customerId: value.contactId, warehouseId: value.warehouseId, notes: value.notes, status: value.status, items: lines.map((line) => ({ productId: line.productId, quantity: Number(line.quantity), unitPrice: line.unitPrice ? Number(line.unitPrice) : undefined })) }) }); onDone(); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to create order."); } finally { setSaving(false); } }
  return <form className="form-stack" onSubmit={submit}>{(error || optionsError) && <div className="form-error">{error || optionsError}</div>}<div className="form-grid two-up"><FormField label={purchase ? "Supplier" : "Customer"}><Select required value={value.contactId} onChange={(event) => update("contactId", event.target.value)}><option value="">Select {purchase ? "supplier" : "customer"}</option>{contacts.map((contact) => <option key={contact.id} value={contact.id}>{contact.name}</option>)}</Select></FormField><FormField label="Warehouse"><Select required value={value.warehouseId} onChange={(event) => update("warehouseId", event.target.value)}><option value="">Select warehouse</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</Select></FormField><FormField label="Status"><Select value={value.status} onChange={(event) => update("status", event.target.value)}><option value="DRAFT">Draft</option><option value={purchase ? "ORDERED" : "CONFIRMED"}>{purchase ? "Ordered" : "Confirmed"}</option></Select></FormField>{purchase && <FormField label="Expected delivery"><Input type="date" value={value.expectedDeliveryDate} onChange={(event) => update("expectedDeliveryDate", event.target.value)} /></FormField>}</div><LineEditor products={products} lines={lines} setLines={setLines} purchase={purchase} /><FormField label="Notes"><textarea className="input textarea" value={value.notes} onChange={(event) => update("notes", event.target.value)} /></FormField><div className="modal-actions"><Button type="button" variant="secondary" onClick={onDone}>Cancel</Button><Button type="submit" disabled={saving}><Save size={15} />{saving ? "Creating..." : `Create ${purchase ? "purchase order" : "sales order"}`}</Button></div></form>;
}

function orderTotal(order: Order) {
  return order.items.reduce((total, item) => total + asNumber(purchaseItemPrice(item)) * ("orderedQuantity" in item ? item.orderedQuantity : item.quantity), 0);
}
function purchaseItemPrice(item: PurchaseOrder["items"][number] | SalesOrder["items"][number]) {
  return "purchaseUnitPrice" in item ? item.purchaseUnitPrice : item.sellingUnitPrice;
}

export function OrdersPage({ kind }: { kind: OrderKind }) {
  const purchase = kind === "purchases"; const [result, setResult] = useState<ListResult<Order> | null>(null); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [modal, setModal] = useState(false);
  const load = () => apiRequest<ListResult<Order>>(`/api/v1/${kind}?pageSize=30${query ? `&search=${encodeURIComponent(query)}` : ""}`).then(setResult).catch((err) => setError(err instanceof Error ? err.message : "Unable to load orders."));
  useEffect(() => { setResult(null); load(); }, [kind, query]);
  return <AppShell><PageHeader eyebrow={`Operations / ${purchase ? "Purchasing" : "Sales"}`} title={purchase ? "Purchase orders" : "Sales orders"} description={purchase ? "Create orders, track receipts, and keep supplier commitments visible." : "Manage customer orders and complete sales with stock validation."} action={<Button onClick={() => setModal(true)}><Plus size={16} /> New {purchase ? "purchase" : "sale"}</Button>} /><Card className="list-card"><Toolbar search={query} onSearch={setQuery} placeholder="Search order number"><span className="result-count">{result?.pagination.total ?? 0} orders</span></Toolbar>{error ? <ErrorState message={error} /> : !result ? <LoadingState /> : result.items.length === 0 ? <EmptyPanel title={`No ${purchase ? "purchase" : "sales"} orders yet`} message="Create an order to start tracking this workflow." onAdd={() => setModal(true)} /> : <Table headers={["Order", purchase ? "Supplier" : "Customer", "Warehouse", "Status", "Value", "Date"]}>{result.items.map((order) => <tr key={order.id}><td><Link className="row-link" to={`/${kind}/${order.id}`}><span className="table-primary">{order.orderNumber}</span><small>{order.items.length} line items</small><ChevronRight size={15} /></Link></td><td>{purchase ? (order as PurchaseOrder).supplier.name : (order as SalesOrder).customer.name}</td><td>{order.warehouse.name}</td><td><StatusBadge status={order.status} /></td><td>{orderTotal(order).toLocaleString()} DZD</td><td>{new Date(order.orderDate).toLocaleDateString()}</td></tr>)}</Table>}</Card><Modal open={modal} title={`New ${purchase ? "purchase order" : "sales order"}`} onClose={() => setModal(false)}><OrderForm kind={kind} onDone={() => { setModal(false); setResult(null); load(); }} /></Modal></AppShell>;
}

function ReceiveModal({ order, onDone }: { order: PurchaseOrder; onDone: () => void }) {
  const [quantities, setQuantities] = useState<Record<string, string>>({}); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); try { await apiRequest(`/api/v1/purchases/${order.id}/receive`, { method: "POST", body: JSON.stringify({ items: order.items.map((item) => ({ itemId: item.id, quantity: Number(quantities[item.id] || 0) })).filter((item) => item.quantity > 0) }) }); onDone(); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to receive goods."); } }
  return <form className="form-stack" onSubmit={submit}>{error && <div className="form-error">{error}</div>}{order.items.map((item) => <div className="receive-row" key={item.id}><div><strong>{item.product.name}</strong><small>{item.receivedQuantity} of {item.orderedQuantity} already received</small></div><Input type="number" min="0" max={item.orderedQuantity - item.receivedQuantity} placeholder="Receive" value={quantities[item.id] ?? ""} onChange={(event) => setQuantities({ ...quantities, [item.id]: event.target.value })} /></div>)}<div className="modal-actions"><Button type="button" variant="secondary" onClick={onDone}>Cancel</Button><Button type="submit"><Truck size={15} /> Receive goods</Button></div></form>;
}

export function OrderDetailPage({ kind }: { kind: OrderKind }) {
  const { id } = useParams(); const navigate = useNavigate(); const purchase = kind === "purchases"; const [order, setOrder] = useState<Order | null>(null); const [error, setError] = useState(""); const [receiveOpen, setReceiveOpen] = useState(false);
  const load = () => id && apiRequest<Order>(`/api/v1/${kind}/${id}`).then(setOrder).catch((err) => setError(err instanceof Error ? err.message : "Unable to load order."));
  useEffect(() => { load(); }, [id, kind]);
  async function completeSale() { if (!order) return; try { await apiRequest(`/api/v1/sales/${order.id}/complete`, { method: "POST" }); load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to complete sale."); } }
  if (error) return <AppShell><PageHeader eyebrow={purchase ? "Purchasing" : "Sales"} title="Order unavailable" back={`/${kind}`} /><ErrorState message={error} /></AppShell>;
  if (!order) return <AppShell><LoadingState /></AppShell>;
  const contact = purchase ? (order as PurchaseOrder).supplier : (order as SalesOrder).customer;
  return <AppShell><PageHeader eyebrow={`Operations / ${purchase ? "Purchasing" : "Sales"}`} title={order.orderNumber} description={`${contact.name} · ${order.warehouse.name}`} back={`/${kind}`} action={purchase && !["RECEIVED", "CANCELLED"].includes(order.status) ? <Button onClick={() => setReceiveOpen(true)}><Truck size={15} /> Receive goods</Button> : !purchase && !["COMPLETED", "CANCELLED"].includes(order.status) ? <Button onClick={completeSale}><Check size={15} /> Complete sale</Button> : undefined} /><div className="detail-grid"><DetailCard title="Order summary"><div className="detail-list"><div><span>Status</span><strong><StatusBadge status={order.status} /></strong></div><div><span>Order date</span><strong>{new Date(order.orderDate).toLocaleDateString()}</strong></div><div><span>{purchase ? "Supplier" : "Customer"}</span><strong>{contact.name}</strong></div><div><span>Warehouse</span><strong>{order.warehouse.name}</strong></div><div><span>Total value</span><strong>{orderTotal(order).toLocaleString()} DZD</strong></div>{purchase && <div><span>Expected delivery</span><strong>{(order as PurchaseOrder).expectedDeliveryDate ? new Date((order as PurchaseOrder).expectedDeliveryDate!).toLocaleDateString() : "—"}</strong></div>}</div>{order.notes && <p className="muted-copy order-notes">{order.notes}</p>}</DetailCard><DetailCard title="Line items"><Table headers={["Product", "Quantity", "Unit price", "Line total"]}>{order.items.map((item) => { const quantity = "orderedQuantity" in item ? item.orderedQuantity : item.quantity; return <tr key={item.id}><td><span className="table-primary">{item.product.name}</span><small>{item.product.sku}</small></td><td>{purchase ? <>{(item as PurchaseOrder["items"][number]).receivedQuantity} / {quantity} received</> : quantity}</td><td>{asNumber(purchaseItemPrice(item)).toLocaleString()} DZD</td><td>{(asNumber(purchaseItemPrice(item)) * quantity).toLocaleString()} DZD</td></tr>; })}</Table></DetailCard></div><Modal open={receiveOpen} title="Receive goods" onClose={() => setReceiveOpen(false)}><ReceiveModal order={order as PurchaseOrder} onDone={() => { setReceiveOpen(false); load(); }} /></Modal></AppShell>;
}